In [1]:
import pandas as pd

pd.options.display.max_columns = None

pd.options.display.max_rows = 40



filename= 'visua_data_canc.csv'

df = pd.read_csv(filename)

In [5]:
# I discovered another way
# pivoting and merging technic
# let us start by creating a new dataframe WITH the categorical data.
categorical_df = df[['patient_id','doctor_name']]
categorical_df.loc[:,'doctor_count'] = 1
categorical_df

/Users/humambarazi/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

     patient_id doctor_name  doctor_count
0       1000025     Dr. Doe             1
1       1002945   Dr. Smith             1
2       1015425     Dr. Lee             1
3       1016277   Dr. Smith             1
4       1017023    Dr. Wong             1
..          ...         ...           ...
694      776715     Dr. Lee             1
695      841769   Dr. Smith             1
696      888820     Dr. Lee             1
697      897471     Dr. Lee             1
698      897471    Dr. Wong             1

[699 rows x 3 columns]

In [6]:
# now we add an extra column to identify which doctor a patient deals with.
doctors_one_hot_encoded = pd.pivot_table(categorical_df,
                                        index = categorical_df.index, #merging it
                                        columns = ['doctor_name'],
                                        values = ['doctor_count']
                                        )
doctors_one_hot_encoded = doctors_one_hot_encoded.fillna(0)

doctors_one_hot_encoded

            doctor_count
doctor_name      Dr. Doe Dr. Lee Dr. Smith Dr. Wong
0                    1.0     0.0       0.0      0.0
1                    0.0     0.0       1.0      0.0
2                    0.0     1.0       0.0      0.0
3                    0.0     0.0       1.0      0.0
4                    0.0     0.0       0.0      1.0
..                   ...     ...       ...      ...
694                  0.0     1.0       0.0      0.0
695                  0.0     0.0       1.0      0.0
696                  0.0     1.0       0.0      0.0
697                  0.0     1.0       0.0      0.0
698                  0.0     0.0       0.0      1.0

[699 rows x 4 columns]

In [22]:
#here the pivot table is generated correctly but it isn't beneficial unless we merge it with the original table
#to do this: some DS use leftmerge. I personally not use it, so i cobine directly.

combined_df = pd.merge(df, doctors_one_hot_encoded, left_index = True, right_index = True, how = 'left')
combined_df

/var/folders/nv/v34jn8hj5llb51ndbwprvb900000gn/T/ipykernel_18010/2642728705.py:4: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (1 levels on the left,2 on the right)
  combined_df = pd.merge(df, doctors_one_hot_encoded, left_index = True, right_index = True, how = 'left')

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,"(doctor_count, Dr. Doe)","(doctor_count, Dr. Lee)","(doctor_count, Dr. Smith)","(doctor_count, Dr. Wong)"
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe,1.0,0.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith,0.0,0.0,1.0,0.0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee,0.0,1.0,0.0,0.0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith,0.0,0.0,1.0,0.0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1,benign,Dr. Lee,0.0,1.0,0.0,0.0
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1,benign,Dr. Smith,0.0,0.0,1.0,0.0
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2,malignant,Dr. Lee,0.0,1.0,0.0,0.0
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1,malignant,Dr. Lee,0.0,1.0,0.0,0.0
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1,malignant,Dr. Wong,0.0,0.0,0.0,1.0

In [23]:
#the column doctor's name is irrelevantt after the merge so we have to drop it.
combined_df = combined_df.drop(columns = ['doctor_name'])
combined_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,"(doctor_count, Dr. Doe)","(doctor_count, Dr. Lee)","(doctor_count, Dr. Smith)","(doctor_count, Dr. Wong)"
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,1.0,0.0,0.0,0.0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,0.0,0.0,1.0,0.0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,0.0,1.0,0.0,0.0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,0.0,0.0,1.0,0.0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1,benign,0.0,1.0,0.0,0.0
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1,benign,0.0,0.0,1.0,0.0
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2,malignant,0.0,1.0,0.0,0.0
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1,malignant,0.0,1.0,0.0,0.0
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1,malignant,0.0,0.0,0.0,1.0

In [20]:
# one of the most important features of data wrangling, is row-sise and columns-wise operations
# here we are asked to create a new columns that categorises (classifies) a patient's cell as normal or abnormal.

def celltypelabel(x):
    if((x['cell_size_uniformity']>5) & (x['cell_shape_uniformity']>5)):
        return('normal')
    else:
        return('abnormal')

In [21]:
combined_df['cell_typelabel'] = combined_df.apply(lambda x: celltypelabel(x), axis =1)
combined_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,"(doctor_count, Dr. Doe)","(doctor_count, Dr. Lee)","(doctor_count, Dr. Smith)","(doctor_count, Dr. Wong)",cell_typelabel
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,1.0,0.0,0.0,0.0,abnormal
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,0.0,0.0,1.0,0.0,abnormal
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,0.0,1.0,0.0,0.0,abnormal
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,0.0,0.0,1.0,0.0,normal
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,0.0,0.0,0.0,1.0,abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3.0,1.0,1,1,3,2,1.0,1.0,1,benign,0.0,1.0,0.0,0.0,abnormal
695,841769,2.0,1.0,1,1,2,1,1.0,1.0,1,benign,0.0,0.0,1.0,0.0,abnormal
696,888820,5.0,10.0,10,3,7,3,8.0,10.0,2,malignant,0.0,1.0,0.0,0.0,normal
697,897471,4.0,8.0,6,4,3,4,10.0,6.0,1,malignant,0.0,1.0,0.0,0.0,normal
698,897471,4.0,8.0,8,5,4,5,10.0,4.0,1,malignant,0.0,0.0,0.0,1.0,normal